# Generated by Django 5.2 on 2025-04-09 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('deactivate_date', models.DateField(blank=True, null=True, verbose_name='비활성화일자')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='전화번호')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='담당/본부')),
                ('team', models.CharField(blank=True, max_length=100, null=True, verbose_name='팀')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='직책')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
