# Generated by Django 5.2 on 2025-04-30 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=99, verbose_name='순서')),
                ('region', models.CharField(max_length=20, verbose_name='담당조직')),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.IntegerField(default=2025)),
            ],
            options={
                'verbose_name': '담당조직',
                'verbose_name_plural': '담당조직',
                'ordering': ['-year', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=99, verbose_name='순서')),
                ('team_name', models.CharField(max_length=20, verbose_name='팀명')),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.IntegerField(default=2024)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.regions')),
            ],
            options={
                'verbose_name': '팀명',
                'verbose_name_plural': '팀명',
                'ordering': ['-year', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='UserFilterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, max_length=100, null=True, verbose_name='팀')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 필터 이력',
                'verbose_name_plural': '사용자 필터 이력',
                'ordering': ['-created_at'],
            },
        ),
    ]
